# Generated by Django 3.1.7 on 2021-04-05 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_remove_userinfo_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(default=datetime.date(2021, 4, 5)),
        ),
    ]
