# Generated by Django 3.2 on 2021-04-07 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_userinfo_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
